:global:
  componentName: control-api
  githubUrl: https://github.com/appuio/component-control-api
  feature_goldenTests: true

docs/antora.yml:
  name: control-api
  title: APPUiO Control API
.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  matrix:
    key: instance
    entries:
      - defaults
