:global:
  componentName: APPUiO Control API
  githubUrl: https://github.com/appuio/component-control-api
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - defaults
      - insecure

.github/workflows/test.yaml:
  test_makeTarget: test -e instance=${{ matrix.instance }}
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
