= Parameters

The parent key for all of the following parameters is `control_api`.

== `namespace`

[horizontal]
type:: string
default:: `appuio-control-api`

The namespace in which to deploy this component.

== `apiserver.apiservice`
type:: dict

== `apiserver.tls`

This key configures encryption of internal traffic, meaning from the Kubernetes API server to our aggregate API sever.

You have the option to provide a custom TLS key and certificate.

If any of the following fields are set to `null` or empty string, the aggregate API server will generate its own certificates.
In that case the connection is still encrypted, but you need to disable TLS verification by setting `insecureSkipTLSVerify` to `true` in the APIService.

=== `apiserver.tls.certSecretName`
type:: string
default:: `control-api-tls`

=== `apiserver.tls.serverCert`
type:: string
default:: "?{vaultkv:${customer:name}/${cluster:name}/${_instance}/apiserver-cert}"

=== `apiserver.tls.serverKey`
type:: string
default:: "?{vaultkv:${customer:name}/${cluster:name}/${_instance}/apiserver-key}"

== `zones`

[horizontal]
type:: dict
default:: `{}`

This key deploys static APPUiO Zone definitions.
Each subkey of `zones` results in the resource's `metadata.name` and contains an object that's an `appuio.io/v1/Zone` spec verbatim.

.Zone configuration
[example]
====
[source,yaml]
----
parameters:
  control_api:
    zones:
      example-zone-1:
        data:
          displayName: Example Zone 1
          features:
            kubernetesVersion: ${dynamic_facts:kubernetesVersion:major}.${dynamic_facts:kubernetesVersion:minor}
            sdnPlugin: OVN-Kubernetes
          urls:
            console: https://console.example.zone
            kubernetesAPI: https://api.example.zone:6443
          cname: cname.example.zone
          defaultAppDomain: apps.example.zone
          gatewayIPs:
          - 100.100.100.100
          cloudProvider:
            name: example
            zones:
              - zone1
            region: region1
----
====

== `cluster_admin_impersonation.oidc_administrator_role`

[horizontal]
type:: string
default:: `admin`

The name of the OpenID Connect role to allow administrator impersonation.
