= Parameters

The parent key for all of the following parameters is `control_api`.

== `namespace`

[horizontal]
type:: string
default:: `appuio-control-api`

The namespace in which to deploy this component.

== `images`

[horizontal]
type:: dictionary
default:: https://github.com/appuio/component-control-api/blob/master/class/defaults.yml[See `class/defaults.yml`]

Dictionary containing the container images used by this component.


== `apiserver.extraArgs`

[horizontal]
type:: list(string)
default:: `[]`

A list of extra command line arguments for the control-api API server deployment.

== `apiserver.apiservice`
type:: dict

This key is applied directly as an `APIService` object.
The `APIService` object instructs the Kubernetes API server to delegate requests to the aggregate API server.

== `apiserver.tls`

This key configures encryption of internal traffic from the Kubernetes API server to the aggregate API sever.

You have the option to provide a custom TLS key and certificate.

=== `apiserver.tls.certSecretName`
type:: string
default:: `control-api-tls`

If this field is set to `null`, the aggregate API server will generate its own certificates.
In that case the connection is still encrypted, but you need to disable TLS verification by setting `insecureSkipTLSVerify` to `true` in the APIService.

=== `apiserver.tls.serverCert`
type:: string
default:: ""

=== `apiserver.tls.serverKey`
type:: string
default:: "?{vaultkv:${customer:name}/${cluster:name}/${_instance}/apiserver-key}"

== `zones`

[horizontal]
type:: dict
default:: `{}`

This key deploys static APPUiO Zone definitions.
Each subkey of `zones` results in the resource's `metadata.name` and contains an object that's an `appuio.io/v1/Zone` spec verbatim.

.Zone configuration
[example]
====
[source,yaml]
----
parameters:
  control_api:
    zones:
      example-zone-1:
        data:
          displayName: Example Zone 1
          features:
            kubernetesVersion: ${dynamic_facts:kubernetesVersion:major}.${dynamic_facts:kubernetesVersion:minor}
            sdnPlugin: OVN-Kubernetes
          urls:
            console: https://console.example.zone
            kubernetesAPI: https://api.example.zone:6443
          cname: cname.example.zone
          defaultAppDomain: apps.example.zone
          gatewayIPs:
          - 100.100.100.100
          cloudProvider:
            name: example
            zones:
              - zone1
            region: region1
----
====

== `cluster_admin_impersonation.oidc_administrator_role`

[horizontal]
type:: string
default:: `admin`

The name of the OpenID Connect role to allow administrator impersonation.

== `username_prefix`

[horizontal]
type:: string
default:: `appuio#`

The prefix used for OIDC users in the Kubernetes API server.


== `controller.extraArgs`

[horizontal]
type:: list(string)
default:: `[]`

A list of extra command line arguments for the control-api controller deployment.


== `idp_adapter.enabled`

[horizontal]
type:: boolean
default:: `false`

Controls if the IDP Adapter should be deployed.


== `idp_adapter.args`

[horizontal]
type:: list
default:: `[]`

Arguments that should be passed to the IDP Adapter.


== `idp_adapter.env`

[horizontal]
type:: list
default:: `{}`
example::
+
[source,yaml]
----
idp_adapter:
  env:
    KEYCLOAK_PASSWORD:
      secretKeyRef:
        name: keycloak-user
        key: password
    DEBUG: "true"
----

Additional environment that should be passed to the IDP Adapter.
If a dict is given `valueFrom:` is assumed.


== `idp_adapter.resources`

[horizontal]
type:: dict
default:: https://github.com/appuio/component-control-api/blob/master/class/defaults.yml[See `class/defaults.yml`]

Resource requests and limits to apply to the IDP Adapter container.


== `secrets`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
secrets:
  keycloak-user:
    stringData:
      username: keycloak-user
      password: keycloak-password
----

A key-value map defining multiple `Secret` for referencing in `secrets`.
Each entry will generate a `Secret` with the key as its name.

